package com.data_management;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

/**
 * A data reader that parses patient data from output files generated by the HealthDataSimulator.
 */
public class FileDataReader implements DataReader {

    private final String directoryPath;

    /**
     * Constructs a FileDataReader with the specified directory path.
     *
     * @param directoryPath the directory containing the simulated output files
     */
    public FileDataReader(String directoryPath) {
        this.directoryPath = directoryPath;
    }

    @Override
    public void readData(DataStorage dataStorage) throws IOException {
        File directory = new File(directoryPath);
        if (!directory.exists() || !directory.isDirectory()) {
            throw new IOException("Directory does not exist or is not a directory: " + directoryPath);
        }

        File[] files = directory.listFiles((dir, name) -> name.endsWith(".txt"));
        if (files == null) {
            return;
        }

        for (File file : files) {
            parseFile(file, dataStorage);
        }
    }

    /**
     * Parses a single file and adds records to the data storage.
     *
     * @param file the file to parse
     * @param dataStorage the storage where data will be stored
     */
    private void parseFile(File file, DataStorage dataStorage) {
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
            while ((line = br.readLine()) != null) {
                parseLine(line, dataStorage);
            }
        } catch (IOException e) {
            System.err.println("Error reading file: " + file.getName());
            e.printStackTrace();
        }
    }

    /**
     * Parses a single line from the output file.
     * Format: "Patient ID: %d, Timestamp: %d, Label: %s, Data: %s"
     *
     * @param line the line to parse
     * @param dataStorage the storage where data will be stored
     */
    private void parseLine(String line, DataStorage dataStorage) {
        try {
            String[] parts = line.split(", ");
            if (parts.length != 4) return;

            int patientId = Integer.parseInt(parts[0].split(": ")[1]);
            long timestamp = Long.parseLong(parts[1].split(": ")[1]);
            String label = parts[2].split(": ")[1];
            String dataValueStr = parts[3].split(": ")[1];

            double measurementValue;
            if (label.equals("Alert")) {
                measurementValue = dataValueStr.equals("triggered") ? 1.0 : 0.0;
            } else {
                measurementValue = Double.parseDouble(dataValueStr.replaceAll("[^\\d.-]", ""));
            }

            dataStorage.addPatientData(patientId, measurementValue, label, timestamp);
        } catch (Exception e) {
            System.err.println("Failed to parse line: " + line);
        }
    }
}
